### ISSUE TITLE
不支持consul了吗？

### ISSUE THREAD

**Issue by ishowfun** [aqa510415008/Ocelot.OrleansHttpGateway#2]
请问，如果要做服务发现该如何做配置？
我觉得还是consul会方便点啊

**Comment by lfzm** [comment]
Orleans 支持consul的，这个就支持的

**Comment by lfzm** [comment]
https://github.com/aqa510415008/Ocelot.OrleansHttpGateway/blob/1cb1e09b27bd9bad461a056b472188e1ac34eaaf/example/OcelotOrleans.AspNetCore/Program.cs#L61

这个地方可以配置不同的服务发现
